# Generated by Django 5.0.6 on 2024-07-05 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synth',
            name='a_d_s_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='synth',
            name='freqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
