# Generated by Django 5.0.6 on 2024-07-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0002_synth_sequencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synth',
            old_name='sequencer',
            new_name='effects',
        ),
    ]
