# Generated by Django 5.0.6 on 2024-07-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0003_rename_sequencer_synth_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='synth',
            name='waveform',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
