# Generated by Django 5.0.6 on 2024-07-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencer',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
