# Generated by Django 5.0.6 on 2024-07-05 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencer', '0002_remove_sequencer_sequencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencer',
            name='sequencer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, null=True, size=None),
        ),
    ]
